<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishTrimmed>false</PublishTrimmed>
		<RootNamespace>Delta</RootNamespace>
		<TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
		<ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="compilerconfig.json" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Assets\app.ico" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="10.0.30" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="compilerconfig.json" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Delta.Application\Delta.Application.csproj" />
	  <ProjectReference Include="..\Delta.Domain\Delta.Domain.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Assets\app.ico" />
	</ItemGroup>
	<ItemGroup>
	  <Content Update="wwwroot\icons\list.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\icons\marker.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\icons\pen-to-square.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\icons\spell-check.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
</Project>
